name: Deploy
on:
    push:
        branches:
            - main
jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Deploy to GitHub Pages
              run: |
                  git config user.name "${{ github.actor }}"
                  git config user.email "${{ github.actor }}@users.noreply.github.com"

                  git branch -D gh-pages || true
                  git checkout -b gh-pages
                  # Add the HTML file (modify the filename if needed)
                  git add page.html

                  git commit -m "Deploy to GitHub Pages"
                  git push --force "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" gh-pages

                  git checkout main
